{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "mesada.fullname" . }}-ingress
  labels:
    {{- include "mesada.labels" . | nindent 4 }}
spec:
  entryPoints: {{ toYaml .Values.ingress.entrypoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "mesada.fullname" . }}-kong
          port: 8000
  tls:
    {{- if .Values.ingress.tls }}
    certResolver: {{ .Values.ingress.certResolver }}
    {{- end }}
{{- end }}
