apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesada.fullname" . }}-secrets
  labels:
    {{- include "mesada.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
  anon-key: {{ .Values.auth.anonKey | quote }}
  service-role-key: {{ .Values.auth.serviceRoleKey | quote }}
